### ISSUE TITLE
Make foldmethod=syntax customizable

### ISSUE THREAD

**Issue by johncf** [arrufat/vala.vim#4]
To change the foldmethod when using this plugin, I'd have to use `after` directory and such. Please make it so that syntax-based folding is not always set based on a global:

```vim
let g:vala_syntax_folding_enabled = 0
```

**Comment by arrufat** [comment]
Hi, do you think that adding:
``` vim
if exists("vala_syntax_folding_enabled")
  set foldmethod=syntax
end
```
to the `syntax.vim` file will do the trick?

**Comment by johncf** [comment]
I think it is better to add:

```vim
augroup arrufat_vala
  autocmd! " clear all autocmds defined within arrufat_vala group
  autocmd FileType vala
      \ if get(g:, 'vala_syntax_folding_enabled', 1) |
      \   set foldmethod=syntax |
      \ endif
augroup END
```

to `plugin/vala.vim`, so that it will be disabled only if I `let g:vala_syntax_folding_enabled = 0`.

_Edit:_ Use an `augroup`.

**Comment by johncf** [comment]
Sorry, there was a mistake in the code.The current version sets the option globally, which is not good. It should have been `setlocal foldmethod=syntax` instead.

**Comment by arrufat** [comment]
Done, thanks for reporting it back :)
