### ISSUE TITLE
Plugin not working for me

### ISSUE THREAD

**Issue by MichaelAquilina** [arrufat/vala.vim#6]
Please excuse the really generic title but I am pretty new to vim and not sure how to debug this package not working.

I have tried it on two different machines (OpenSUSE Tumbleweed and Ubuntu Gnome 16.10) and both failed to highlight vala files for me.

I have the following line in my `~/.vimrc` file:

```
Bundle "arrufat/vala.vim"
```

Vundle is correctly setup because all other packages work.

Could you advise on what the next steps should be to figure out what is going on? My vim version is `7.4`

**Comment by arrufat** [comment]
Hi! It's been a while since I tried [Vundle], but according to the website, you must use `Plugin` instead of `Bundle`. I'm not sure this is what is causing the issue, though... But I'm afraid I can't help you with just that information :(

[Vundle]: https://github.com/VundleVim/Vundle.vim

**Comment by MichaelAquilina** [comment]
I believe it `Bundle` is just an alias for `Plugin` so both should work fine. What is the recommended way for installing `vala.vim`?

**Comment by arrufat** [comment]
In theory, any plugin manager should work, although I've only used [vim-plug]. This is my configuration for vim-plug (much simpler than others, that's why I switched from Vundle some time ago):

``` vim
call plug#begin('~/.vim/plugged')
Plug 'arrufat/vala.vim'
call plug#end()

" bonus: update all plugins and vim-plug itself
command! PU PlugUpdate | PlugUpgrade
```

[vim-plug]: https://github.com/junegunn/vim-plug

**Comment by MichaelAquilina** [comment]
Guess I'll have to give it a go and find out! :)

**Comment by MichaelAquilina** [comment]
I've also tried this with vim-plug and it doesnt seem to work :/ Any tips on how I could debug this? Are there some logs I could check?

**Comment by MichaelAquilina** [comment]
So I tried this on neovim and it worked without any issue. Is it possible its just not working on standard vim?

**Comment by arrufat** [comment]
I don't know... I'm using on the Vim package that comes with Arch Linux.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MichaelAquilina** [comment]
Quite odd :/ I tried vim on both Ubuntu Gnome 16.10 and OpenSUSE Tumbleweed and both dint work :S

**Comment by MichaelAquilina** [comment]
Actually scratch that, it seems to be working on vim now too :s I have no idea what's changed since then
